command:
  - "uvicorn"
  - "server.app:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8080"

env:
  - name: ENV
    value: "production"
  - name: PROJECTS_BASE_DIR
    value: "./projects"
  - name: ENABLED_SKILLS
    value: "databricks-python-sdk,spark-declarative-pipelines,synthetic-data-generation"
  # Database - set LAKEBASE_PG_URL via app secrets
  # - name: LAKEBASE_PG_URL
  #   valueFrom:
  #     secretKeyRef:
  #       name: lakebase-pg-url
  #       key: url
