# Databricks Apps deployment configuration
command:
  - uvicorn
  - app:app
  - --host
  - 0.0.0.0
  - --port
  - "8000"

env:
  - name: DATABRICKS_HOST
    value: https://your-workspace.azuredatabricks.net/serving-endpoints
  - name: DATABRICKS_TOKEN
    valueFrom: DATABRICKS_TOKEN
  - name: ANTHROPIC_CUSTOM_HEADERS
    value: "x-databricks-disable-beta-headers: true"
  - name: DISABLE_PROMPT_CACHING
    value: "1"
  - name: CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS
    value: "1"
